name: hello world

on:
  push:
      branches:
          - main

jobs:
    hello:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4

      - name: Run Linter Check
        uses: devops-actions/actionlint@v0.1.3

      - name: run echo
        run: echo "Hello, world!"