name: hello world

on:
  push:
      branches:
          - main

jobs:
    hello:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Run Linter Check
        uses: rhysd/actionlint-action@v3

      - name: run echo
        run: echo "Hello, world!"